version: '3.9'
services:
  react_access:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/react_access"
      - "/opt/react_access/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

      
